version: '3.8'

services:

  app:
    container_name: backend-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_NAME: ${MONGO_NAME}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_COLLECTION: ${MONGO_COLLECTION}

    env_file:
      - config/.env


  mongo:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - 27017:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_NAME: ${MONGO_NAME}
      MONGO_COLLECTION: ${MONGO_COLLECTION}

  integration:
    build:
      context: .
      dockerfile: tests/integration_tests/Dockerfile
    container_name: integration
    depends_on:
      - app
      - mongo
    volumes:
        - ./tests/integration_tests:/app/tests/integration_tests
    command: [ "go", "test", "./tests/integration_tests" ]


volumes:
  mongodb_data:

networks:
  default:
    name: my_network