version: '3.8'

services:

  app:
    container_name: backend-container
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_NAME: ${MONGO_NAME}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_COLLECTION: ${MONGO_COLLECTION}

    env_file:
      - .env


  mongo:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_NAME: ${MONGO_NAME}
      MONGO_COLLECTION: ${MONGO_COLLECTION}


volumes:
  mongodb_data:

networks:
  default:
    name: my_network